version: '2'
services:
  ca:
    image: curtisdslone/zerotrustca:latest
    volumes: 
      - ca_data:/opt
    container_name: ca_srv
    hostname: ca_srv
    domainname: scada.local
  ldap:
    depends_on:
      - ca
    image: curtisdslone/zerotrustldap:latest
    volumes: 
      - ca_data:/opt
    container_name: ldap_srv
    hostname: ldap_srv
    domainname: scada.local
volumes:
  ca_data: {}