#!/bin/bash
touch init.ldif;
user=$(base64 certs/fred-user-id.cer);
admin=$(base64 certs/fred-adm-id.cer);
device=$(base64 certs/net-mon.cer);

echo "# Root of Dir Tree" >> init.ldif;
echo "dn: dc=scada,dc=local" >> init.ldif;
echo "description: Scada.local for python webapp." >> init.ldif;
echo "dc: scada" >> init.ldif;
echo "o: SCADA" >> init.ldif;
echo "objectClass: top" >> init.ldif;
echo "objectClass: dcObject" >> init.ldif;
echo "objectClass: organization" >> init.ldif;
echo "#Subtree for Devices" >> init.ldif;
echo "dn: ou=Devices,dc=scada,dc=local" >> init.ldif;
echo "ou: Devices" >> init.ldif;
echo "description: Trusted network devices" >> init.ldif;
echo "objectClass: organizationalUnit" >> init.ldif;
echo "#Subtree for Users" >> init.ldif;
echo "dn: ou=Users,dc=scada,dc=local" >> init.ldif;
echo "ou: Users" >> init.ldif;
echo "description: Trusted network users" >> init.ldif;
echo "objectClass: organizationalUnit" >> init.ldif;
echo "#Subtree for Admins" >> init.ldif;
echo "dn: ou=Admins,dc=scada,dc=local" >> init.ldif;
echo "ou: Admins" >> init.ldif;
echo "description: Trusted network Admins" >> init.ldif;
echo "objectClass: organizationalUnit" >> init.ldif;
echo "# Fred Flinstone User" >> init.ldif;
echo "dn: cn=Fred Flintstone,ou=Users,dc=scada,dc=local" >> init.ldif;
echo "cn: Fred Flintstone" >> init.ldif;
echo "sn: Flintstone" >> init.ldif;
echo "uid: fred.flintstone" >> init.ldif;
echo "userCertificate;binary:: " + $user >> init.ldif;
echo "objectclass: top" >> init.ldif;
echo "objectclass: person" >> init.ldif;
echo "objectclass: organizationalPerson" >> init.ldif;
echo "objectclass: inetOrgPerson" >> init.ldif;
echo "#Fred Flintstone Admin" >> init.ldif;
echo "dn: cn=Fred Flintstone,ou=Admins,dc=scada,dc=local" >> init.ldif;
echo "cn: Fred Flintstone" >> init.ldif;
echo "sn: Flintstone" >> init.ldif;
echo "uid: fred.flintstone.adm" >> init.ldif;
echo "userCertificate;binary:: " + $admin >> init.ldif;
echo "objectclass: person" >> init.ldif;
echo "objectclass: organizationalPerson" >> init.ldif;
echo "objectclass: inetOrgPerson" >> init.ldif;
echo "#West Device" >> init.ldif;
echo "dn: cn=West Device,ou=Devices,dc=scada,dc=local" >> init.ldif;
echo "cn: West Device" >> init.ldif;
echo "sn: Device" >> init.ldif;
echo "uid: west.device" >> init.ldif;
echo "userCertificate;binary:: " + $device >> init.ldif;
echo "objectclass: top" >> init.ldif;
echo "objectclass: person" >> init.ldif;
echo "objectclass: organizationalPerson" >> init.ldif;
echo "objectclass: inetOrgPerson" >> init.ldif
echo "finished"