version: '2'
services:
  ca:
    image: ca:latest
    volumes: 
      - certVol:/opt/CERT
      - 
    container_name: ca
    hostname: ca
    domainname: scada.local
  cert:
    depends_on:
      - ca
    image: alpine
    volumes: 
      - certVol:/opt/
    container_name: cert
    hostname: cert
    domainname: scada.local
volumes:
  certVol: {}
  dataVol: {}
  webVol: {}
  authVol: {}
