version: '2'
services:
  ca:
    image: curtisdslone/zerotrustca:latest
    volumes: 
      - ldapVol:/opt/ldap
      - CAVol:/opt
    container_name: ca_srv
    hostname: ca_srv
    domainname: scada.local
  ldap:
    depends_on:
      - ca
    image: curtisdslone/zerotrustldap:latest
    volumes: 
      - ldapVol:/etc/openldap
    container_name: ldap_srv
    hostname: ldap_srv
    domainname: scada.local
volumes:
  ldapVol: {}
  CAVol: {}
